services:
  health-app:
    build: .
    container_name: service-vps-modul1-ncc
    # Restart Policy: Otomatis nyala jika server reboot
    environment:
      - PORT=5000
    # Port Configuration: Akses dari luar via 3000
    ports:
<<<<<<< HEAD
<<<<<<< HEAD
      - "80:5000"
=======
      - "8080:5000"
>>>>>>> 5a0c9c6 (Initial commit: tes endpoint health)
=======
      - "3000:5000"
    restart: always
>>>>>>> ef06a76 (Feat: menambahkan untuk poin plus)
