services:
  health-app:
    build: .
    container_name: service-vps-modul1-ncc
    environment:
      - PORT=5000
    # Port Configuration: Akses dari luar via 3000
    ports:
      - "3000:5000"
    restart: always